### ISSUE TITLE
Can not parse <strong> tag and all images losed

### ISSUE THREAD

**Issue by ghost** [gaojiuli/tomd#1]

**Comment by elliotgao2** [comment]
Please paste your code snippets.

**Comment by ghost** [comment]
[《Django By Example》第一章 中文 翻译 （个人学习，渣翻）.zip](https://github.com/gaojiuli/tomd/files/1058151/Django.By.Example.zip)

I convert this html file to md. Use the code pasted from readme

**Comment by elliotgao2** [comment]
I have add supporting of strong , but what do you mean "all images losed".

**Comment by ghost** [comment]
Seems can not parse `<img>` to `![]()`

**Comment by elliotgao2** [comment]
The `<img>` tag should wrappered by  `<p>` tag because It's an inline element. Please check again.

**Comment by ducdetronquito** [comment]
Hi there !

Would it be possible to make a new release of Tomd on PyPI ? For now the \<strong> tags are still not converted :cry:

Thanks in advance :+1:

**Comment by elliotgao2** [comment]
@ducdetronquito New version 0.1.3 had been released on PyPI.
